language: cpp
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: windows
      env:
        - VCPKG_DEFAULT_TRIPLET="x64-windows"
        - CMAKE_BUILD_EXTRA_ARGS="--config Debug"
        - CTEST_EXTRA_ARGS="-C Debug"

before_install:
    - eval "${MATRIX_EVAL}"

install:
- sh ./.ci/osx-install-gcc.sh
- sh ./.ci/windows-upgrade-to-vs2019.sh
- sh ./.ci/setup-vcpkg.sh

cache:
  directories:
  - external/vcpkg

script:
- mkdir build
- cd build
- cmake ..
- cmake --build . ${CMAKE_BUILD_EXTRA_ARGS}
- ctest ${CTEST_EXTRA_ARGS}

