name: CMake

on:
  workflow_dispatch:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: '3.11'

    - name: Install build dependencies from PyPI
      run: |
        python -m pip install meson cmake ninja

    - name: Configure Meson (POSIX)
      # Configure meson for POSIX environments
      if: startsWith(matrix.os, 'windows') != true 
      run: cd ${{github.workspace}} && meson setup builddir
      
    - name: Configure Meson (Windows)
      # Configure meson for Windows environments
      if: startsWith(matrix.os, 'windows') == true 
      run: cd ${{github.workspace}} && meson setup builddir --vsenv

    - name: Build
      # Build your program with the given configuration
      run: meson compile -C ${{github.workspace}}/builddir --verbose

    - name: Test
      working-directory: ${{github.workspace}}/builddir
      # Execute tests defined by meson test configuration.
      run: meson test -v -j 1
